### ISSUE TITLE
Create custom Line Pages endpoint

### ISSUE THREAD

**Issue by albertkun** [LACMTA/metro-api-v2#147]
Things to figure out:
- [x] #151
- [ ] How are we going to come up with a list of stops, and can we do this in phases?
  - [ ] Start with the trip with the most number of stops. maybe using the `trip_id` with the highest `stop_sequence` value.
  - [ ] Create a table of unique stop patterns for each `route_id`? Would that just be the `shape_id`?

Specs:
- [ ] Takes in a `route_id` for rail, example: **801** or `route_code` for bus. need to work this out more.
- [ ] Endpoint response should be:
  - an array of objects, one for each stop along the route
  - each object should include:
    - `route_id`
    - `stop_id` - from `stop_times`
    - `stop_name` - from `stops`
    - stop coordinate - from `stops`
    - `direction_id` - from `trips`
    - day type (Weekday, Saturday, Sunday) - parsed from `service_id` from `trips`
    - `departure_time` - from `stop_times`, separated by each day type
    - `stop_sequence` - not completely sure how we will determine this

Example:

``` js
[
  {
    route_id: `801`,
    stop_id: `80214`,
    stop_name: 'Union Station - Metro Red & Purple Lines',
    coordinate: .....,
    stop_sequence: {
      direction_0: {
        weekday: 1,
        saturday: 1,
        sunday: 1
      },
      direction_1: {
        weekday: 14
        saturday: 14
        sunday: 14
      }
    }
    stop_times: {
      direction_0: {
        weekday: [
          '05:01:00',
          ...
        ],
        saturday: [
          '05:01:00',
          ...
        ],
        sunday: [
          '05:01:00',
          ...
        ]
      },
      direction_1: {
        weekday: [
          '05:01:00',
          ...
        ],
        saturday: [
          '05:01:00',
          ...
        ],
        sunday: [
          '05:01:00',
          ...
        ]
      }
    }
  },
  {
   ...
  }
]
```

**Comment by albertkun** [comment]
### Progress report

Current endpoint is `/{agency_id}/line_stops/{route}`

Added primary/foreign keys in the database to join the data

The initial table that starts the query is `trips` using the the **route_id** field.

Looking into creating the SQL statements to query the required data, will need to join the following tables:

- `stops`
- `stop_times`

**Comment by albertkun** [comment]
Progress report 1/17/2023

- Successfully queried the resulting data with the following SQL query:
``` sql
select DISTINCT on (stop_times.stop_id) stop_times.stop_id, trips.route_id,max(stop_sequence), stop_times.departure_time,stop_times.stop_headsign, stops.stop_name, stops.geometry,trips.service_id,stop_times.stop_sequence,trips.direction_id
from metro_api.stop_times
inner join trips on trips.trip_id = stop_times.trip_id
inner join stops on stops.stop_id = stop_times.stop_id
group by stop_times.stop_id,stop_times.stop_headsign,trips.route_id,trips.direction_id,trips.service_id,stop_times.stop_sequence,stop_times.departure_time,stops.stop_name,stops.geometry;

```

### Questions

How to best structure to SQL query for the data we need!

### WIP

We now need to generate the create tables using the correct join method (i.e. 1-Many, Many-to-Many, Many to one)

I am assuming we need to have the `departure_times` be more than just one row of data unlike what is seen below:

|stop_id|route_id|max|departure_time|stop_headsign|stop_name|geometry|service_id|stop_sequence|direction_id|
|-------|--------|---|--------------|-------------|---------|--------|----------|-------------|------------|
|1|108-13167|62|05:01:00|108 - Slauson - Paramount|Paramount / Slauson|POINT (-118.113113 33.973248)|DEC22-D05CAR-1_Weekday|62|0|
|10012|202-13167|18|05:34:00|202 - Del Amo Station|Greenleaf / Alameda|POINT (-118.218247 33.881153)|DEC22-D18CAR-1_Weekday|18|1|

More like this:

|stop_id|departure_time|
|-------|--------------|
|1|05:01:00|
|1|05:15:00|
|1|05:19:00|
|1|05:33:00|
|1|05:46:00|
|1|05:53:00|
|1|05:58:00|
|1|05:59:00|
|1|06:03:00|
|1|06:11:00|
|1|06:20:00|
|1|06:24:00|
|1|06:25:00|
|1|06:43:00|
|1|06:44:00|
|1|06:46:00|
|1|06:48:00|
|1|06:58:00|
|1|07:01:00|
|1|07:11:00|
|1|07:13:00|
|1|07:16:00|
|1|07:29:00|
|1|07:31:00|

**Comment by albertkun** [comment]
### Update

|stop_id|trip_id|max|
|-------|-------|---|
|1|10108003130533-DEC22|103|
|10012|10202000570519-DEC22|18|
|10033|10110002821847-DEC22|64|
|10034|10110002821847-DEC22|63|
|10035|10110002821847-DEC22|65|
|10036|10110002821847-DEC22|68|
|stop_id|trip_id|max|
|-------|-------|---|
|1|10108003130533-DEC22|103|
|10012|10202000570519-DEC22|18|
|10033|10110002821847-DEC22|64|
|10034|10110002821847-DEC22|63|
|10035|10110002821847-DEC22|65|
|10036|10110002821847-DEC22|68|

**Comment by matikin9** [comment]
For reference, we are diagramming in this FigJam: https://www.figma.com/file/yd7LvYgzD5WPqHgc06BLKC/Line-Pages-Data-Diagramming?node-id=0%3A1&t=NiDHAxjIW3ofW8kL-1

**Comment by matikin9** [comment]
``` js
{
  route_id: '',
  direction_0: 
  {
    weekday:
    [
      {
        stop_id: '',
        stop_name: '',
        departure_times: 
        [
          {
            trip_id: '',
            departure_time: ''
          },{
            trip_id: '',
            departure_time: ''
          },{
            trip_id: '',
            departure_time: ''
          },{
            trip_id: '',
            departure_time: ''
          }
        ]
      },{
        stop_id: '',
        stop_name: '',
        departure_times: 
        [
          {
            trip_id: '',
            departure_time: ''
          },{
            trip_id: '',
            departure_time: ''
          },{
            trip_id: '',
            departure_time: ''
          },{
            trip_id: '',
            departure_time: ''
          }
        ]
      }
    ],
    saturday: 
    [
      {}
    ],
    sunday:
    [
      {}
    ]
  },
  direction_1: 
  {
    weekday:
    [
      {}
    ],
    saturday: 
    [
      {}
    ],
    sunday:
    [
      {}
    ]
  }
}
```

**Comment by matikin9** [comment]
for SoFi Stadium and Dodger Stadium Express buses, use the daytype:

``` js
    all: 
    [
    ]
```

**Comment by matikin9** [comment]
We need to create two separate lists of `trip_id`s, based on `direction_id`, to find a max `stop_sequence` for each direction.
