### ISSUE TITLE
Spec out endpoints for additional features based on latest Figma designs

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#152]

**Comment by albertkun** [comment]
Which figma designs? Is it this one?? 

https://www.figma.com/file/yd7LvYgzD5WPqHgc06BLKC/Line-Pages-Data-Diagramming?node-id=0%3A1&t=NiDHAxjIW3ofW8kL-1

**Comment by matikin9** [comment]
This one:

https://www.figma.com/proto/YvK6ye3Ut0YuPwCWIGHqdW/Exemplifi?node-id=1%3A23983&scaling=min-zoom&page-id=1%3A2&starting-point-node-id=1%3A23983&show-proto-sidebar=1

The specific features we discussed in our meeting with Exemplifi are here under "Design Discussion": https://docs.google.com/document/d/1m_42XfyouTyzODnWrCMHf5buem9VYLbSg_syHFhJTMw/edit?usp=sharing

**Comment by albertkun** [comment]
What is it for? Line pages? Schedules? Would be helpful to have that in the title! :)

**Comment by matikin9** [comment]
Part of the discussion was that we will need to change the way the times get returned.

**Comment by albertkun** [comment]
Closed with the merge of #165
