### ISSUE TITLE
Create Custom Schedule Pages Endpoint

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#153]
THIS ISSUE IS STILL A DRAFT

This endpoint will power the redesigned Schedule page as defined in this Figma: https://www.figma.com/file/hGHBpaYBoZB6ZSJdEat0tj/Schedules?node-id=89%3A144&t=iALhZCxiEG38Thrg-0

It needs to pull in and store data that is currently in Metro.net's WordPress site, which can be accessed via the WP REST API.

It needs to provide:
- [ ] agency type (Metro Rail vs Metro Bus) - `agency_id`
- [ ] line label (letter for rail and number for bus) - `route_code` or `route_id` - for `route_code` we may want to maintain a separate table that gets updated during GTFS processing to associate `route_id`s with `route_code`s for bus because `route_code` is in the `stop_times` table.
- [ ] line description separated by terminus 1, terminus 2, 'via' description - this can be pulled from the Line Overrides content from the metro.net WP API but will need to be manually broken out as 3 separate fields
- [ ] `route_id`
- [ ] color - `route_color` from GTFS `routes` table for rail. Manually set for bus.
- [ ] icon image url - link to iconography repo for rail?

Structure:

``` js
[
    {
        agency_id: 'LACMTA_rail',
        routes: [
            {
                line_label: 'A Line',
                route_id: '801',
                color: '#001122',
                icon_url: 'https://....',
                description: {
                    terminus_1: 'Downtown Los Angeles',
                    terminus_2: 'Long Beach',
                    via: ''
                }
            },{
                ...
            }
        ]
    },
    {
        agency_id: 'LACMTA',
        routes: [
            ...
        ]
    }
]
```

**Comment by albertkun** [comment]
closed by #162
