### ISSUE TITLE
Need API keys for ArcGIS/ESRI maps

### ISSUE THREAD

**Issue by anithegregorian** [LACMTA/metro-api-v2#180]
hi @albertkun @matikin9 ,

The current prototype on Codesandbox is based on Leaflet with ArcGIS tiles, it's not fully implemented on ArcGIS yet. Although I did try to get some head start with https://lacmta.github.io/realtime-map/examples/ and as this seemed to be a pre-build vector map, it's probably not going to work for displaying dynamic mapping with points.

Here's an [example](https://developers.arcgis.com/esri-leaflet/samples/showing-a-basemap/) code of ArcGIS with Leaflet

It would be great if you could share the API keys from ArcGIS for live implementation:

![alt text](https://developers.arcgis.com/documentation/static/fcd286a08a555d01cbaf4231584bb69b/8de58/api-keys-management.png)

**Comment by albertkun** [comment]
@anithegregorian currently trying to get keys from our ArcGIS Admin! Thank you for your patience!

**Comment by albertkun** [comment]
Sent a follow-up email this morning to Kenneth, will keep updating!

**Comment by albertkun** [comment]
@anithegregorian I sent the key to Vinod on Monday!
