### ISSUE TITLE
Bus routes in schedule detail repeating twice

### ISSUE THREAD

**Issue by Eturisaichand** [LACMTA/metro-api-v2#190]
![screenshot (2)](https://user-images.githubusercontent.com/71026182/225107227-1a7c74de-9427-4230-aa61-15ed394505b3.jpg)
https://tk0qe2.csb.app/schedules_detail.html?route=2&agency=LACMTA

@albertkun

**Comment by matikin9** [comment]
We need to talk to Joe & Rollin to see if we can come to a good resolution for this issue.  While the data is technically not wrong, it does not make for a good user experience that these two stop names are identical. Does the bus AVA provide a distinction between these 2 back-to-back stops?  Technically one stop is next to N Beverly Glen Blvd and the other is next to S Beverly Glen Blvd, so perhaps we can make that distinction?
