### ISSUE TITLE
Some Bus lines are missing comparing live site

### ISSUE THREAD

**Issue by Eturisaichand** [LACMTA/metro-api-v2#191]
![image](https://user-images.githubusercontent.com/71026182/225108574-8c042d69-cd32-4d02-91aa-19d1b4be4f04.png)
@albertkun Most of the stations starts with */* are missing in dev comparing live site metro.net

**Comment by albertkun** [comment]
@Eturisaichand the line numbers are listed in the `route_overview` endpoint using the `route_code` field:

### All Metro
https://api.metro.net/all/route_overview

### Bus
https://api.metro.net/LACMTA/route_overview?route_code=all

### Rail
https://api.metro.net/LACMTA_Rail/route_overview?route_code=all

Can you check to make sure that the schedules page is using the right API endpoint and field to populate the schedules.html page?
