### ISSUE TITLE
Bus timimgs in schedule details are showing wrong comparing to live site

### ISSUE THREAD

**Issue by Eturisaichand** [LACMTA/metro-api-v2#192]
![image](https://user-images.githubusercontent.com/71026182/225114497-4bd0830a-863e-41fc-9e50-e388c155fcba.png)
![image](https://user-images.githubusercontent.com/71026182/225114617-06aad58f-3444-43d2-9836-6e1acaffd372.png)
https://www.metro.net/riding/schedules/?line=2-13167#
https://tk0qe2.csb.app/schedules_detail.html?route=2&agency=LACMTA

@albertkun this is one of the example for this

**Comment by albertkun** [comment]
@Eturisaichand can you provide us the exact time that you checked this data in Pacific time zone? there are two issues at play on the front end:

1. The display of the data on the front end as there `4 hrs 181 minutes` is an incorrect display.
2. Conversion of the data with different time zones is causing the client to display the data incorrectly.

RE: 2. If you checked this at 12pm India Standard Time, there seems to a time zone conversion issue.

I would recommend checking to see the logic of the frontend to see how the time zone is affecting the display of the schedules data.
