### ISSUE TITLE
Store Swiftly data in a database for querying

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#24]
MBTA is:
- Transitioning to running containers on AWS Fargate.
- Running anywhere from 3-5 servers (not containers) at a given time, and serving ~500 million API requests per month.
- Polling the TripUpdates feed every 10 seconds, the VehiclePositions every second, and Alerts every minute. 

We've set up a Postgres DB already, but we may want to go with SQLite and do in-memory querying.  SQLite is a file-based DB that we can connect to and run queries on.  Data is saved and persistent.

On the Lightsail container service that currently runs our API, we would modify the scheduled process to pull data from Swiftly and write it to a local SQLite DB file on the container.  The SQLite file would then be accessed when needed.

- [ ] what DB option to go with?
- [ ] define tables for the data

**Comment by albertkun** [comment]
Closed because... postgresql rocks!!!!!
