### ISSUE TITLE
Include `direction_id`

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#277]
Include `direction_id` in these endpoints.

Needs to be correctly joined within the data loading service.  Right now it is only setting `direction_id` to `0`.

## Websocket

wss://dev-metro-api-v2.ofhq3vd1r7une.us-west-2.cs.amazonlightsail.com/LACMTA/live/trip_detail/route_code/2

`wss://dev-metro-api-v2.ofhq3vd1r7une.us-west-2.cs.amazonlightsail.com/{agency_id}/live/trip_detail/route_code/{route_code}`

## REST API

https://api.metro.net/LACMTA/trip_detail/route_code/2?geojson=false

`https://api.metro.net/{agency_id}/trip_detail/route_code/{route_code}?geojson=false`

**Comment by albertkun** [comment]
`direction_id` working for all endpoints (websockets and rest) as per #295 #290
