### ISSUE TITLE
Analyze Routes

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#313]
# Jupyter Notebook

We want to compare the stops for each trip/shape associated with a route_id in each direction in order to present this information to the Service Planners and better understand the lines.

**Comment by albertkun** [comment]
Completed! 😄  Will upload the Jupyter Notebook on Monday after I clean it up!

[combine_get_stop_ids_for_each_route_ids_number_of_shapes_per_direction_greater_than_1_with_route_id_with_stop_id_differences.csv](https://github.com/LACMTA/metro-api-v2/files/12705267/combine_get_stop_ids_for_each_route_ids_number_of_shapes_per_direction_greater_than_1_with_route_id_with_stop_id_differences.csv)
