### ISSUE TITLE
Create additional route analysis output

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#317]
- [x] Create additional `.csv` output with:
  * route_id
  * direction_id
  * count of unique shape_id

Example:

| route_id | direction_id | count of unique shape_id |
|-- |--|--|
| 268-13168 | 0 | 1 |
| 268-13168 | 1 | 1 |
| 10-13168 | 0 | 14 |
| 10-13168 | 1 | 9 |

- [x] Add `route_code` (from `stop_times`) to `route_analysis_per_shape_id` so we can distinguish between the lines for the routes that have sister lines.

- [x] clean up the whitespace in the arrays

**Comment by albertkun** [comment]
@matikin9 I propose to amend adding `route_code` to the table as follows:

| route_id | direction_id |route_code| count of unique shape_id |
|-- |--|--|--|
| 268-13168 | 0 |268| 1 |
| 268-13168 | 1 |268| 1 |
| 10-13168 | 0 | 10| 14 |
| 10-13168 | 1 | 10 |9 |
|10-13168|0|48|7
