### ISSUE TITLE
API Endpoint Research

### ISSUE THREAD

**Issue by albertkun** [LACMTA/metro-api-v2#4]
### Standards

- https://amdigital-co-uk.github.io/6.-Engineering/Quality-Standards/Endpoint-Naming-Conventions/

#### CTA

- gettime
- getdirections
- getstops
- getservicebulletins
- getpredictions
- getvehicles

Source: https://www.transitchicago.com/assets/1/6/cta_Bus_Tracker_API_Developer_Guide_and_Documentation_20160929.pdf

**Comment by matikin9** [comment]
Closing this out since I think we're on a good track already!
