### ISSUE TITLE
Some lines throwing Internal Server Error

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#462]
Examples:

* Line 20 - https://lametro.wpengine.com/riding/schedules?line=20&agency=LACMTA
* Line 910 - https://lametro.wpengine.com/riding/schedules?line=910&agency=LACMTA

![image](https://github.com/LACMTA/metro-api-v2/assets/1873072/ec3ed669-2fb8-495f-96e5-6a105ba6b06e)

**Comment by albertkun** [comment]
Fixed: this was an issue with the rows being duplicated in the database, so the endpoint did not know which one to return.

![image](https://github.com/LACMTA/metro-api-v2/assets/8574425/e2473240-07f7-447f-94da-4d2f950f46d7)
