### ISSUE TITLE
Internal Server Error when using Static endpoints

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#514]
https://api.metro.net/LACMTA/trips/10910002151411-DEC23

![image](https://github.com/LACMTA/metro-api-v2/assets/1873072/0ff2ce17-9dd1-4f71-8d58-08855aed8195)

**Comment by albertkun** [comment]
Merging to prod and closing as issue is fixed.
![image](https://github.com/LACMTA/metro-api-v2/assets/8574425/a8eab9ab-da37-4fba-ba93-b30ad1d405b0)
