### ISSUE TITLE
Internal Server error with `stop_times` endpoint

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#517]
![image](https://github.com/LACMTA/metro-api-v2/assets/1873072/4dc1b2c5-e792-41d8-b2cd-6a567294cc9a)
![image](https://github.com/LACMTA/metro-api-v2/assets/1873072/0c44b020-675c-4815-8210-0b995c0f16fa)

**Comment by albertkun** [comment]
closed with #530
