### ISSUE TITLE
mysterious map / title issue

### ISSUE THREAD

**Issue by albertkun** [LACMTA/metro-api-v2#539]
![image](https://github.com/LACMTA/metro-api-v2/assets/8574425/2c485340-7585-4504-a220-c3a39b9af72c)

## Issue

@anithegregorian

- [x] Title not displaying
- [x] Map not displaying

## Cause?

Potentially a change in the API?

## Debug attempts

- Tried to change back the API data structure, didn't work ⭕ 
- Looked at the console log ⭕ 
- Looked at the calls to the API ⭕ 

![image](https://github.com/LACMTA/metro-api-v2/assets/8574425/62a6467d-2137-4982-8c0b-098139704170)

**Comment by anithegregorian** [comment]
@albertkun the issue arose due to refactoring of `shape_id` to `shape_ids` (array), and removing JSON.parse() for geometries. For some routes it's working, quite a few are returning *Internal Server Error*, as you can see below:

![image](https://github.com/LACMTA/metro-api-v2/assets/143655/db9ab996-d3d7-40a3-9a6c-9420d6d1b3f7)

**Comment by albertkun** [comment]
@anithegregorian ok! that makes sense! should i change it back to `shape_id` then?

**Comment by anithegregorian** [comment]
That won't be an issue, my system time was 10:46PM (night), now it's using 24hrs format (morning in US)

I had to change these lines (not sure if change is required)

![image](https://github.com/LACMTA/metro-api-v2/assets/143655/a78ccd2d-e00b-436a-b864-242316fc6e53)

**Comment by albertkun** [comment]
ohhh, ok, gotcha! sorry about that! and thank you for the quick turn around!🙏 unless you have any other comments regarding this, i will mark this issue as resolved!

**Comment by anithegregorian** [comment]
@albertkun go ahead with closing the issue, I also noticed that the payload size is reduced drastically for geometries, a huge improvement! thx

**Comment by albertkun** [comment]
@anithegregorian no porblem! thank you for flagging the geojson issue! it really was a huge drop in payload size thanks to you! :)
