### ISSUE TITLE
Additional field values to filter GTFS-rt data for

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#71]
More fields we can add filters for:

- Trip Updates
  - `route_id`
  - `stop_id`

- Vehicle Positions
  - `trip_id`
  - `trip_route_id`
  - `stop_id`

_Originally posted by @matikin9 in https://github.com/LACMTA/metro-api-v2/issues/70#issuecomment-1284630304_

**Comment by albertkun** [comment]
the route handling for both `@app.get("/{agency_id}/trip_updates/{field_name}/{field_value}` and `@app.get("/{agency_id}/vehicle_positions/{field_name}/{field_value}",tags=["Real-Time data"])` is generic so can already handle this. was there something else you were thinking of?
