### ISSUE TITLE
Current_status to reflect the VehicleStopStatus Enum values

### ISSUE THREAD

**Issue by matikin9** [LACMTA/metro-api-v2#74]
`current_status` values should reflect the [`VehicleStopStatus` Enum](https://gtfs.org/realtime/reference/#enum-vehiclestopstatus) with the values:

- `INCOMING_AT`
- `STOPPED_AT`
- `IN_TRANSIT_TO`

_Originally posted by @matikin9 in https://github.com/LACMTA/metro-api-v2/issues/69#issuecomment-1284641273_

**Comment by albertkun** [comment]
did you want to change this at the database level or the json returned level?

**Comment by matikin9** [comment]
Details about the Enums! https://github.com/google/transit/issues/291
